services:
  db:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: stronkpassword123
      POSTGRES_DB: schoolmoneydb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
